#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Author:
#Cedric H. David, 2017-2018


#*******************************************************************************
#System specifications for Travis CI
#*******************************************************************************
matrix:
  include:
    - os: linux
      language: python
      python:
      - "2.7"
      sudo: required


#*******************************************************************************
#Environment variables for different tests on multiple Travis CI workers
#*******************************************************************************
env:
- TST_PUB_DWNL='./tst_pub_dwnl_David_etal_201x_SER.sh' TST_PUB_REPR='./tst_pub_repr_David_etal_201x_SER.sh'


#*******************************************************************************
#Before installing SHBAAM
#*******************************************************************************
before_install:

#-------------------------------------------------------------------------------
#Create .netrc file for secure downloads (users need their own credentials)
#-------------------------------------------------------------------------------
- echo "machine urs.earthdata.nasa.gov login malaya@uci.edu password Aircarnot1!" >> ~/.netrc

#-------------------------------------------------------------------------------
#Specific to Linux
#-------------------------------------------------------------------------------
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get --version             ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y $(grep -v -E '(^#|^$)' requirements.apt) ; fi


#-------------------------------------------------------------------------------
#Specific to OSX
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
#General environment details
#-------------------------------------------------------------------------------
- uname -a
- echo $TRAVIS_OS_NAME
- which python
- python --version
- ls -l $(which python)
- ls -l $(which -a python)
- which pip
- pip --version
- ls -l $(which pip)
- ls -l $(which -a pip)


#*******************************************************************************
#Installing SHBAAM
#*******************************************************************************
install:
- sudo pip install -r requirements.pip


#*******************************************************************************
#Testing SHBAAM
#*******************************************************************************
script:
- cd ./tst/
- echo $TST_PUB_DWNL && $TST_PUB_DWNL
- echo $TST_PUB_REPR && $TST_PUB_REPR 
